export interface Album {
    AlbumId: string;
    AlbumTitle: string;
    ArtistName: string;
    TrackCount: number;
    Genres: string;
    MinPrice: string;
    MaxPrice: string;
    AvgPrice: string;
}

export const sampleAlbums: Album[] = [
    { AlbumId: "1", AlbumTitle: "Abbey Road", ArtistName: "The Beatles", TrackCount: 17, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "2", AlbumTitle: "Thriller", ArtistName: "Michael Jackson", TrackCount: 9, Genres: "Pop", MinPrice: "12.99", MaxPrice: "24.99", AvgPrice: "18.99" },
    { AlbumId: "3", AlbumTitle: "The Dark Side of the Moon", ArtistName: "Pink Floyd", TrackCount: 10, Genres: "Rock", MinPrice: "14.99", MaxPrice: "29.99", AvgPrice: "22.49" },
    { AlbumId: "4", AlbumTitle: "The Bodyguard", ArtistName: "Whitney Houston", TrackCount: 12, Genres: "Soundtrack", MinPrice: "9.99", MaxPrice: "19.99", AvgPrice: "14.99" },
    { AlbumId: "5", AlbumTitle: "Back in Black", ArtistName: "AC/DC", TrackCount: 10, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "6", AlbumTitle: "The Eminem Show", ArtistName: "Eminem", TrackCount: 18, Genres: "Hip Hop", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "7", AlbumTitle: "Come Away with Me", ArtistName: "Norah Jones", TrackCount: 14, Genres: "Jazz", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "8", AlbumTitle: "Confessions", ArtistName: "Usher", TrackCount: 20, Genres: "R&B", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "9", AlbumTitle: "Falling into You", ArtistName: "Celine Dion", TrackCount: 15, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "10", AlbumTitle: "Jagged Little Pill", ArtistName: "Alanis Morissette", TrackCount: 13, Genres: "Rock", MinPrice: "9.99", MaxPrice: "18.99", AvgPrice: "14.49" },
    { AlbumId: "11", AlbumTitle: "The Marshall Mathers LP", ArtistName: "Eminem", TrackCount: 18, Genres: "Hip Hop", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "12", AlbumTitle: "Double Live", ArtistName: "Garth Brooks", TrackCount: 26, Genres: "Country", MinPrice: "14.99", MaxPrice: "24.99", AvgPrice: "19.99" },
    { AlbumId: "13", AlbumTitle: "No Fences", ArtistName: "Garth Brooks", TrackCount: 11, Genres: "Country", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "14", AlbumTitle: "Led Zeppelin IV", ArtistName: "Led Zeppelin", TrackCount: 8, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "15", AlbumTitle: "21", ArtistName: "Adele", TrackCount: 11, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "16", AlbumTitle: "Come On Over", ArtistName: "Shania Twain", TrackCount: 16, Genres: "Country", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "17", AlbumTitle: "Appetite for Destruction", ArtistName: "Guns N' Roses", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "18", AlbumTitle: "Bat Out of Hell", ArtistName: "Meat Loaf", TrackCount: 7, Genres: "Rock", MinPrice: "9.99", MaxPrice: "18.99", AvgPrice: "14.49" },
    { AlbumId: "19", AlbumTitle: "Backstreet Boys", ArtistName: "Backstreet Boys", TrackCount: 14, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "20", AlbumTitle: "Hysteria", ArtistName: "Def Leppard", TrackCount: 12, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "21", AlbumTitle: "Saturday Night Fever", ArtistName: "Bee Gees", TrackCount: 15, Genres: "Soundtrack", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "22", AlbumTitle: "Rumours", ArtistName: "Fleetwood Mac", TrackCount: 11, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "23", AlbumTitle: "The Wall", ArtistName: "Pink Floyd", TrackCount: 26, Genres: "Rock", MinPrice: "14.99", MaxPrice: "24.99", AvgPrice: "19.99" },
    { AlbumId: "24", AlbumTitle: "Purple Rain", ArtistName: "Prince", TrackCount: 9, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "25", AlbumTitle: "Physical Graffiti", ArtistName: "Led Zeppelin", TrackCount: 15, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "26", AlbumTitle: "Supernatural", ArtistName: "Santana", TrackCount: 12, Genres: "Rock", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "27", AlbumTitle: "Hotel California", ArtistName: "Eagles", TrackCount: 9, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "28", AlbumTitle: "The Joshua Tree", ArtistName: "U2", TrackCount: 11, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "29", AlbumTitle: "Tapestry", ArtistName: "Carole King", TrackCount: 12, Genres: "Pop", MinPrice: "9.99", MaxPrice: "18.99", AvgPrice: "14.49" },
    { AlbumId: "30", AlbumTitle: "Millennium", ArtistName: "Backstreet Boys", TrackCount: 14, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "31", AlbumTitle: "Achtung Baby", ArtistName: "U2", TrackCount: 12, Genres: "Rock", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "32", AlbumTitle: "Synchronicity", ArtistName: "The Police", TrackCount: 11, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "33", AlbumTitle: "Hybrid Theory", ArtistName: "Linkin Park", TrackCount: 12, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "34", AlbumTitle: "Fallen", ArtistName: "Evanescence", TrackCount: 13, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "35", AlbumTitle: "American Idiot", ArtistName: "Green Day", TrackCount: 13, Genres: "Rock", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "36", AlbumTitle: "Licensed to Ill", ArtistName: "Beastie Boys", TrackCount: 12, Genres: "Hip Hop", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "37", AlbumTitle: "Californication", ArtistName: "Red Hot Chili Peppers", TrackCount: 15, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "38", AlbumTitle: "Meteora", ArtistName: "Linkin Park", TrackCount: 12, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "39", AlbumTitle: "Use Your Illusion I", ArtistName: "Guns N' Roses", TrackCount: 16, Genres: "Rock", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "40", AlbumTitle: "Use Your Illusion II", ArtistName: "Guns N' Roses", TrackCount: 14, Genres: "Rock", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "41", AlbumTitle: "Nevermind", ArtistName: "Nirvana", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "42", AlbumTitle: "In Utero", ArtistName: "Nirvana", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "43", AlbumTitle: "Ten", ArtistName: "Pearl Jam", TrackCount: 11, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "44", AlbumTitle: "Vs.", ArtistName: "Pearl Jam", TrackCount: 12, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "45", AlbumTitle: "Vitalogy", ArtistName: "Pearl Jam", TrackCount: 14, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "46", AlbumTitle: "No Code", ArtistName: "Pearl Jam", TrackCount: 12, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "47", AlbumTitle: "Yield", ArtistName: "Pearl Jam", TrackCount: 13, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "48", AlbumTitle: "Binaural", ArtistName: "Pearl Jam", TrackCount: 13, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "49", AlbumTitle: "Riot Act", ArtistName: "Pearl Jam", TrackCount: 15, Genres: "Rock", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "50", AlbumTitle: "Pearl Jam", ArtistName: "Pearl Jam", TrackCount: 13, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "51", AlbumTitle: "Backspacer", ArtistName: "Pearl Jam", TrackCount: 11, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "52", AlbumTitle: "Lightning Bolt", ArtistName: "Pearl Jam", TrackCount: 12, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "53", AlbumTitle: "Gigaton", ArtistName: "Pearl Jam", TrackCount: 12, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "54", AlbumTitle: "Dark Horse", ArtistName: "Pearl Jam", TrackCount: 11, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "55", AlbumTitle: "OK Computer", ArtistName: "Radiohead", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "56", AlbumTitle: "Kid A", ArtistName: "Radiohead", TrackCount: 10, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "57", AlbumTitle: "Amnesiac", ArtistName: "Radiohead", TrackCount: 11, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "58", AlbumTitle: "Hail to the Thief", ArtistName: "Radiohead", TrackCount: 14, Genres: "Rock", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "59", AlbumTitle: "In Rainbows", ArtistName: "Radiohead", TrackCount: 10, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "60", AlbumTitle: "The King of Limbs", ArtistName: "Radiohead", TrackCount: 8, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "61", AlbumTitle: "A Moon Shaped Pool", ArtistName: "Radiohead", TrackCount: 11, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "62", AlbumTitle: "The Bends", ArtistName: "Radiohead", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "63", AlbumTitle: "Pablo Honey", ArtistName: "Radiohead", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "64", AlbumTitle: "Blackstar", ArtistName: "David Bowie", TrackCount: 7, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "65", AlbumTitle: "The Rise and Fall of Ziggy Stardust", ArtistName: "David Bowie", TrackCount: 11, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "66", AlbumTitle: "Let's Dance", ArtistName: "David Bowie", TrackCount: 8, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "67", AlbumTitle: "Station to Station", ArtistName: "David Bowie", TrackCount: 6, Genres: "Rock", MinPrice: "9.99", MaxPrice: "18.99", AvgPrice: "14.49" },
    { AlbumId: "68", AlbumTitle: "Heroes", ArtistName: "David Bowie", TrackCount: 10, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "69", AlbumTitle: "Low", ArtistName: "David Bowie", TrackCount: 11, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "70", AlbumTitle: "Hunky Dory", ArtistName: "David Bowie", TrackCount: 11, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "71", AlbumTitle: "Aladdin Sane", ArtistName: "David Bowie", TrackCount: 10, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "72", AlbumTitle: "Diamond Dogs", ArtistName: "David Bowie", TrackCount: 11, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "73", AlbumTitle: "Young Americans", ArtistName: "David Bowie", TrackCount: 10, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "74", AlbumTitle: "Lodger", ArtistName: "David Bowie", TrackCount: 10, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "75", AlbumTitle: "Scary Monsters", ArtistName: "David Bowie", TrackCount: 10, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "76", AlbumTitle: "Never Let Me Down", ArtistName: "David Bowie", TrackCount: 9, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "77", AlbumTitle: "Outside", ArtistName: "David Bowie", TrackCount: 19, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "78", AlbumTitle: "Earthling", ArtistName: "David Bowie", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "79", AlbumTitle: "Hours", ArtistName: "David Bowie", TrackCount: 11, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "80", AlbumTitle: "Heathen", ArtistName: "David Bowie", TrackCount: 12, Genres: "Rock", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "81", AlbumTitle: "Reality", ArtistName: "David Bowie", TrackCount: 16, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "82", AlbumTitle: "The Next Day", ArtistName: "David Bowie", TrackCount: 14, Genres: "Rock", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "83", AlbumTitle: "Lemonade", ArtistName: "Beyoncé", TrackCount: 12, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "84", AlbumTitle: "Dangerously in Love", ArtistName: "Beyoncé", TrackCount: 15, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "85", AlbumTitle: "B'Day", ArtistName: "Beyoncé", TrackCount: 14, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "86", AlbumTitle: "I Am... Sasha Fierce", ArtistName: "Beyoncé", TrackCount: 15, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "87", AlbumTitle: "4", ArtistName: "Beyoncé", TrackCount: 12, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "88", AlbumTitle: "Beyoncé", ArtistName: "Beyoncé", TrackCount: 14, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "89", AlbumTitle: "Everything Is Love", ArtistName: "The Carters", TrackCount: 9, Genres: "Pop", MinPrice: "10.99", MaxPrice: "19.99", AvgPrice: "15.49" },
    { AlbumId: "90", AlbumTitle: "Homecoming: The Live Album", ArtistName: "Beyoncé", TrackCount: 40, Genres: "Live", MinPrice: "14.99", MaxPrice: "24.99", AvgPrice: "19.99" },
    { AlbumId: "91", AlbumTitle: "Renaissance", ArtistName: "Beyoncé", TrackCount: 16, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "92", AlbumTitle: "Cowboy Carter", ArtistName: "Beyoncé", TrackCount: 27, Genres: "Country", MinPrice: "13.99", MaxPrice: "23.99", AvgPrice: "18.99" },
    { AlbumId: "93", AlbumTitle: "The Fame", ArtistName: "Lady Gaga", TrackCount: 15, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "94", AlbumTitle: "Born This Way", ArtistName: "Lady Gaga", TrackCount: 17, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "95", AlbumTitle: "Artpop", ArtistName: "Lady Gaga", TrackCount: 15, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "96", AlbumTitle: "Cheek to Cheek", ArtistName: "Lady Gaga & Tony Bennett", TrackCount: 15, Genres: "Jazz", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "97", AlbumTitle: "Joanne", ArtistName: "Lady Gaga", TrackCount: 14, Genres: "Pop", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" },
    { AlbumId: "98", AlbumTitle: "A Star Is Born", ArtistName: "Lady Gaga & Bradley Cooper", TrackCount: 19, Genres: "Soundtrack", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "99", AlbumTitle: "Chromatica", ArtistName: "Lady Gaga", TrackCount: 16, Genres: "Pop", MinPrice: "12.99", MaxPrice: "22.99", AvgPrice: "17.99" },
    { AlbumId: "100", AlbumTitle: "Love for Sale", ArtistName: "Lady Gaga & Tony Bennett", TrackCount: 12, Genres: "Jazz", MinPrice: "11.99", MaxPrice: "21.99", AvgPrice: "16.99" }
];

// Convert sample data to array of arrays format for DataTables
export const sampleAlbumsArray: (string | number | boolean)[][] = sampleAlbums.map(album => [
    album.AlbumId,
    album.AlbumTitle,
    album.ArtistName,
    album.TrackCount,
    album.Genres,
    album.MinPrice,
    album.MaxPrice,
    album.AvgPrice,
    album.AlbumId // For the action column
]);