import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PersistentLayoutClient from "./persistent-layout-client";
import '@styles/main.scss';

// Define the global theme constant
export const GLOBAL_THEME = "webLightTheme"; // specified initial value

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="preload" href="/fluent.svg" as="image" />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <PersistentLayoutClient multiple={false} initialTheme={GLOBAL_THEME}>
                    {children}
                </PersistentLayoutClient>
            </body>
        </html>
    );
}
